movies/urls.py
from django.urls import path
from . import views #relative path

app_name = "movies"
# url configuration
urlpatterns = [
  path('',views.index,name='index'), # here i am using reference not function calling when use make request django take resposibility
  path("<int:movie_id>",views.detail,name='detail')
]
# here mepty string nothing but root of this app like ''

movies/models.py
# from django.db import models # this contains all the database activites

# # Create your models here.

from django.db import models
from django.utils import timezone

class Genre(models.Model):
    name = models.CharField(max_length=255,null=False)

    def __str__(self): # like to string method in java\
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255,null=False)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField() 
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)  # we can make relationsship between genre and movie
    date_created =  models.DateTimeField(default=timezone.now)

#  models are nothing but table naes in movies database now wwe have to store that models in dabase called dqlite3

movies/views.py
from django.http import HttpResponse,Http404
from django.shortcuts import render,get_object_or_404
from .models import Movie

# Create your views here.
# create main page in app mention index name
def index(request):
  movies = Movie.objects.all() # to gell all list of movies
  # output = ",".join([m.title for m in movies])
  # # select * from movies_movie
  # Movie.objects.filter(release_year=1984)
  # # select * from movies_movie where
  # Movie.objects.get(id=1)
  return render(request,'movies/index.html',{'movies':movies})

  # return HttpResponse(output)

# to format our data we are using render model it rendel the data like html,json format
def detail(request,movie_id):
 
    movie = get_object_or_404(Movie,pk=movie_id)
    return render(request,"movies/detail.html",{"movie":movie})



  

movies/templates/movies/detail.html
{% extends "base.html" %} {% block content %}
<dl>
  <dt>Title</dt>
  <dd>{{movie.title}}</dd>
  <dt>Genre</dt>
  <dd>{{movie.genre}}</dd>
  <dt>Stock</dt>
  <dd>{{movie.number_in_stock}}</dd>
</dl>

{% endblock %}

movies/templates/movies/index.html
{% extends "base.html" %} {% block content %}

<table class="table table-bordered table-hover">
  <thread>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Stock</th>
      <th>Daily Rate</th>
    </tr>
  </thread>
  <tdbody>
    {% for movie in movies %}

    <tr>
      <td>
        <a href="{% url 'movies:detail' movie.id %}">{{movie.title}}</a>
      </td>
      <td>{{movie.genre}}</td>
      <td>{{movie.number_in_stock}}</td>
      <td>{{movie.daily_rate}}</td>
    </tr>
    {% endfor %}
  </tdbody>
</table>
{% endblock %}