movies/urls.py
from django.urls import path
from . import views #relative path

app_name = "movies"
# url configuration
urlpatterns = [
  path('',views.index,name='index'), # here i am using reference not function calling when use make request django take resposibility
  path("<int:movie_id>",views.detail,name='detail')
]
# here mepty string nothing but root of this app like ''

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']



# # Tastypie is a popular library in the Django ecosystem that facilitates building RESTful APIs.     

movies/models.py
# from django.db import models # this contains all the database activites

# # Create your models here.

from django.db import models
from django.utils import timezone

class Genre(models.Model):
    name = models.CharField(max_length=255,null=False)

    def __str__(self): # like to string method in java\
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255,null=False)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField() 
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)  # we can make relationsship between genre and movie
    date_created =  models.DateTimeField(default=timezone.now)

#  models are nothing but table naes in movies database now wwe have to store that models in dabase called dqlite3

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse,Http404
from django.shortcuts import render,get_object_or_404
from .models import Movie

# Create your views here.
# create main page in app mention index name
def index(request):
  movies = Movie.objects.all() # to gell all list of movies
  # output = ",".join([m.title for m in movies])
  # # select * from movies_movie
  # Movie.objects.filter(release_year=1984)
  # # select * from movies_movie where
  # Movie.objects.get(id=1)
  return render(request,'movies/index.html',{'movies':movies})

  # return HttpResponse(output)

# to format our data we are using render model it rendel the data like html,json format
def detail(request,movie_id):
 
    movie = get_object_or_404(Movie,pk=movie_id)
    return render(request,"movies/detail.html",{"movie":movie})



  

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Vidly</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <style>
      /* Custom Navbar Styling */
      .navbar {
        background-color: #f8f9fa; /* Light grey background */
      }

      .navbar-brand {
        display: block;
        font-weight: bold;
        color: #343a40; /* Dark text color */
        margin-left: 20px; /* Adjust this value as needed */
      }
      /* Main Content Styling */
      main {
        margin-top: 20px; /* Add some space between navbar and content */
      }

      /* Custom Button Styling */
      .btn-custom {
        background-color: #007bff; /* Blue button color */
        color: #fff; /* White text color */
        border: none;
      }

      .btn-custom:hover {
        background-color: #0056b3; /* Darker blue on hover */
      }

      /* Footer Styling */
      footer {
        background-color: #343a40; /* Dark background color */
        color: #fff; /* Light text color */
        padding: 20px 0; /* Padding top and bottom */
        text-align: center;
        position: fixed;
        bottom: 0;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">Vidly</a>
    </nav>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer>
      <div class="container">
        <p>&copy;2024 Your Company. All rights reserved.</p>
      </div>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %} {% block content %}
<a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}